version: '2'
services:
  grafana_graphite:
    build: .
    image: grafana
    container_name: kamon-grafana-dashboard
    ports:
      - '80:80'
      - '81:81'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
      - '2004:2004'
      - '2013:2013'
      - '2014:2014'
      - '2023:2023'
      - '2024:2024'
      - '2033:2033'
      - '2034:2034'
      - '2043:2043'
      - '2044:2044'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
